###################################################################################################
#
# Makefile
#
# Used to build and run C++ test programs.
#
#
###################################################################################################
.PHONY: default build clean install 

.SILENT:

include $(SAFIR_SDK)/data/build/make_vs_setup

default: build

build : 
	$(VC_SETUP) & devenv.com /build release EntityStresser\EntityStresser.vcproj
	$(VC_SETUP) & devenv.com /build release RequestStresser\RequestStresser.vcproj
	$(VC_SETUP) & devenv.com /build release MessageStresser\MessageStresser.vcproj
	$(VC_SETUP) & devenv.com /build release MessageLatencies\MessageLatencies.vcproj
	$(VC_SETUP) & devenv.com /build release RequestLatencies\RequestLatencies.vcproj
	$(VC_SETUP) & devenv.com /build release EntityReceptionVerifier\EntityReceptionVerifier.vcproj
	$(VC_SETUP) & devenv.com /build release EntityIntegrityChecker\EntityIntegrityChecker.vcproj


install: build


clean: 
	-rm -rf EntityStresser\Debug EntityStresser\Release
	-rm -rf RequestStresser\Debug RequestStresser\Release
	-rm -rf MessageStresser\Debug MessageStresser\Release
	-rm -rf MessageLatencies\Debug MessageLatencies\Release
	-rm -rf RequestLatencies\Debug RequestLatencies\Release
	-rm -rf EntityReceptionVerifier\Debug EntityReceptionVerifier\Release
	-rm -rf EntityIntegrityChecker\Debug EntityIntegrityChecker\Release
	-rm -f $(SAFIR_RUNTIME)\bin\EntityStresser.exe
	-rm -f $(SAFIR_RUNTIME)\bin\EntityStresserd.exe
	-rm -f $(SAFIR_RUNTIME)\bin\RequestStresser.exe
	-rm -f $(SAFIR_RUNTIME)\bin\RequestStresserd.exe
	-rm -f $(SAFIR_RUNTIME)\bin\MessageStresser.exe
	-rm -f $(SAFIR_RUNTIME)\bin\MessageStresserd.exe
	-rm -f $(SAFIR_RUNTIME)\bin\RequestLatencies.exe
	-rm -f $(SAFIR_RUNTIME)\bin\RequestLatenciesd.exe
	-rm -f $(SAFIR_RUNTIME)\bin\MessageLatencies.exe
	-rm -f $(SAFIR_RUNTIME)\bin\MessageLatenciesd.exe
	-rm -f $(SAFIR_RUNTIME)\bin\EntityReceptionVerifier.exe
	-rm -f $(SAFIR_RUNTIME)\bin\EntityReceptionVerifierd.exe
	-rm -f $(SAFIR_RUNTIME)\bin\EntityIntegrityChecker.exe
	-rm -f $(SAFIR_RUNTIME)\bin\EntityIntegrityCheckerd.exe

