/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class safir_application_Library */

#ifndef _Included_safir_application_Library
#define _Included_safir_application_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     safir_application_Library
 * Method:    SetProgramName
 * Signature: (Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_SetProgramName
  (JNIEnv *, jclass, jstring, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TraceAppendStringPrefix
 * Signature: (J[B[Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_TraceAppendStringPrefix
  (JNIEnv *, jclass, jlong, jbyteArray, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TraceAppendCharPrefix
 * Signature: (JB[Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_TraceAppendCharPrefix
  (JNIEnv *, jclass, jlong, jbyte, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TraceSyncBuffer
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_TraceSyncBuffer
  (JNIEnv *, jclass, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TraceFlushBuffer
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_TraceFlushBuffer
  (JNIEnv *, jclass, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TracePrefixAdd
 * Signature: (Ljava/lang/String;[J[Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_TracePrefixAdd
  (JNIEnv *, jclass, jstring, jlongArray, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TracePrefixSetEnabled
 * Signature: (JZ[Z)V
 */
JNIEXPORT void JNICALL Java_safir_application_Library_TracePrefixSetEnabled
  (JNIEnv *, jclass, jlong, jboolean, jbooleanArray);

/*
 * Class:     safir_application_Library
 * Method:    TracePrefixIsEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_safir_application_Library_TracePrefixIsEnabled
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
