/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class safir_swreports_Library */

#ifndef _Included_safir_swreports_Library
#define _Included_safir_swreports_Library
#ifdef __cplusplus
extern "C" {
#endif

this file needs to be regenerated! run "run_jni.bat"!
/*
 * Class:     safir_swreports_Library
 * Method:    SendFatalErrorReport
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_safir_swreports_Library_SendFatalErrorReport
  (JNIEnv *, jclass, jstring, jstring, jstring, jbooleanArray);

/*
 * Class:     safir_swreports_Library
 * Method:    SendErrorReport
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_safir_swreports_Library_SendErrorReport
  (JNIEnv *, jclass, jstring, jstring, jstring, jbooleanArray);

/*
 * Class:     safir_swreports_Library
 * Method:    SendResourceReport
 * Signature: (Ljava/lang/String;ZLjava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_safir_swreports_Library_SendResourceReport
  (JNIEnv *, jclass, jstring, jboolean, jstring, jbooleanArray);

/*
 * Class:     safir_swreports_Library
 * Method:    SendProgrammingErrorReport
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_safir_swreports_Library_SendProgrammingErrorReport
  (JNIEnv *, jclass, jstring, jstring, jstring, jbooleanArray);

/*
 * Class:     safir_swreports_Library
 * Method:    SendProgramInfoReport
 * Signature: (Ljava/lang/String;[Z)V
 */
JNIEXPORT void JNICALL Java_safir_swreports_Library_SendProgramInfoReport
  (JNIEnv *, jclass, jstring, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
