###################################################################################################
#
# Makefile
#
# run "make help" to get the currently defined targets.
#
# 050809/HESU: Created
# 051006/HESU: Split the implementation to a "build" and a "test" phase.
# 070115/LAHA: Rewrite
#
###################################################################################################
.PHONY: default help build install clean generate

.SILENT:

DOU_FILES := $(wildcard data/*.dou)
DOM_FILES := $(wildcard data/*.dom)
DOB_FILES := $(DOU_FILES) $(DOM_FILES)

default: build


help:
	echo make         -- build the executables
	echo make install -- copy the executables to $(SAFIR_RUNTIME)\bin
	echo make clean   -- remove binaries and object files
	echo generate	  -- copy the dou files and run make

build:
#	$(MAKE) -C ada -f Makefile.win32
	$(MAKE) -C cpp -f Makefile.win32
	$(MAKE) -C dotnet -f Makefile.win32
#	$(MAKE) -C java -f Makefile.win32
	$(MAKE) -C Sequencer -f Makefile.win32
	$(MAKE) -C StressTests -f Makefile.win32

install:
#	$(MAKE) -C ada install -f Makefile.win32
	$(MAKE) -C cpp install -f Makefile.win32
	$(MAKE) -C dotnet install -f Makefile.win32
#	$(MAKE) -C java install -f Makefile.win32
	$(MAKE) -C Sequencer install -f Makefile.win32
	$(MAKE) -C StressTests install -f Makefile.win32
	-xcopy /Y *.bat $(SAFIR_RUNTIME)\bin

clean:
#	-$(MAKE) -C ada clean -f Makefile.win32
	-$(MAKE) -C cpp clean -f Makefile.win32
	-$(MAKE) -C dotnet clean -f Makefile.win32
#	-$(MAKE) -C java clean -f Makefile.win32
	-$(MAKE) -C Sequencer clean -f Makefile.win32
	-$(MAKE) -C StressTests clean -f Makefile.win32

generate:
	-xcopy /Y data\\*.dou $(SAFIR_SDK)\dots\dots_generated
	-xcopy /Y data\\*.dom $(SAFIR_SDK)\dots\dots_generated
#	attrib -R $(SAFIR_SDK)\dots\dots_generated\\*
	$(foreach file, $(patsubst data%,$(SAFIR_SDK)\dots\dots_generated%, $(DOB_FILES)), touch $(file))
	cd $(SAFIR_SDK)\dots\dots_generated && make