set(CPACK_GENERATOR NuGet)
set(CPACK_COMPONENTS_ALL NuGet)
set(CPACK_NUGET_COMPONENT_INSTALL True)

# Fix version string for NuGet – replace any '~' with '-'
string(REPLACE "~" "-" SAFIR_VERSION_STRING_NUGET "${SAFIR_VERSION_STRING}")

set(CPACK_PACKAGE_NAME SafirSDKCore.api)
set(CPACK_NUGET_NUGET_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_VERSION "${SAFIR_VERSION_STRING_NUGET}")
set(CPACK_PACKAGE_VENDOR "Saab AB")
set(CPACK_NUGET_PACKAGE_AUTHORS "Saab AB")
set(CPACK_PACKAGE_DESCRIPTION ".NET interfaces for Safir SDK Core")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://www.safirsdkcore.com")
set(CPACK_NUGET_PACKAGE_REPOSITORY_URL "https://github.com/SafirSDK/safir-sdk-core.git")
set(CPACK_NUGET_PACKAGE_REPOSITORY_TYPE git)
set(CPACK_NUGET_PACKAGE_LICENSE_EXPRESSION "LGPL-3.0-only")
set(CPACK_NUGET_PACKAGE_README docs/readme.md)
set(CPACK_NUGET_PACKAGE_TFMS ${DOTNET_FRAMEWORK_TFM})

include(CPack)
