###################################################################################################
#
# Makefile
#
# Used to build and run C++ test programs.
#
# 050909/HESU: Created
# 051006/HESU: Restructured according to the makefile in the directory above.
# 051010/LAHA: Moved command line flags to variables to increase readability.
#              Added default and run targets.
# 070113/LAHA: Rewrite
#
###################################################################################################
.PHONY: default build clean install 

.SILENT:

include $(SAFIR_SDK)/data/build/make_vs_setup

default: build

build : 
	$(VC_SETUP) & devenv.com /build release dose_test_sequencer.vcproj

install: build
	copy Release\dose_test_sequencer.exe $(SAFIR_RUNTIME)\bin

clean: 
	-rm -rf debug release
	-rm -f $(SAFIR_RUNTIME)\bin\dose_test_sequencer.exe



# INCLUDE_DIRS = %SAFIR_SDK%\include
# DEFINES=/D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_MBCS"
# CL_FLAGS=/nologo /I $(INCLUDE_DIRS) $(DEFINES) /EHsc /MD /GS /W4 /WX /Wp64

# TARGET_EXECUTABLE_NAME = dose_test_cpp.exe

# SOURCES = $(wildcard *.cpp)
# HEADERS = $(wildcard *.h)

# #this is used to get a rebuild when something has changed in dots
# DOTS_INSTALLED = $(SAFIR_SDK)\dots\dots_generated\install_flag


# TEST_OUTPUT_FILENAME = ..\new_output\cpp.txt

# default: build

# test: dirs build
# 	$(TARGET_EXECUTABLE_NAME) >$(TEST_OUTPUT_FILENAME)

# dirs:
# 	-mkdir ..\new_output >\nul 2>\nul

# build: $(TARGET_EXECUTABLE_NAME)

# $(TARGET_EXECUTABLE_NAME): $(SOURCES) $(HEADERS) $(DOTS_INSTALLED)
# 	$(VC_SETUP) > \nul & cl $(CL_FLAGS) $(SOURCES) /Fe$(TARGET_EXECUTABLE_NAME) /link /LIBPATH:%SAFIR_SDK%\lib 

# clean:
# 	-del /Q $(TEST_OUTPUT_FILENAME) *.obj *.exe *.pdb *.idb *.ilk *.ncb >\nul 2>\nul
# 	-rmdir /S /Q Debug Release >\nul 2>\nul



