 

CREATE TABLE tblolibtest (
  UNITID int(11) NOT NULL,
  CALLSIGN varchar(6) DEFAULT NULL,
  COMBATREADINESS int(11) DEFAULT NULL,
  COMBATREADINESSDESCRIPTION varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  UNITSIZEID varchar(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  UNITIDENTITYID varchar(50) CHARACTER SET utf8 COLLATE utf8_romanian_ci DEFAULT NULL,
  LATITUDE double DEFAULT NULL,
  LONGITUDE double DEFAULT NULL,
  SPEED float DEFAULT NULL,
  COURSE float DEFAULT NULL,
  MEASUREMENTTIME timestamp NULL DEFAULT NULL,
  ISALIVE int(11) DEFAULT NULL,
  ALARGEINT bigint(20) DEFAULT NULL,
  PRIMARY KEY (`UNITID`)
);

CREATE TABLE tblolibtestbinary (
  ID int(11) NOT NULL,
  DATA binary(255) DEFAULT NULL,
  PRIMARY KEY (ID)
); 

CREATE TABLE tblolibtestblob (
  ID int(11) NOT NULL,
  DATA mediumblob,
  PRIMARY KEY (ID)
);

CREATE TABLE tblolibtestnclob (
  ID int(11) NOT NULL,
  DATA longtext,
  PRIMARY KEY (ID)
);

CREATE TABLE tblperftest (
  TypeID bigint(20) DEFAULT NULL,
  InstanceNo int(11) DEFAULT NULL,
  data varchar(2100) DEFAULT NULL
) 
 